"""Structured expected PostgreSQL schema catalog for migration tests."""

EXPECTED_KEY_CONSTRAINTS = {
    "pk_api_clients": ("api_clients", "p", ("id",), None, (), None),
    "pk_chunk_embeddings": ("chunk_embeddings", "p", ("id",), None, (), None),
    "pk_chunks": ("chunks", "p", ("id",), None, (), None),
    "pk_client_source_grants": (
        "client_source_grants",
        "p",
        ("client_id", "source_profile_id"),
        None,
        (),
        None,
    ),
    "pk_document_contents": ("document_contents", "p", ("id",), None, (), None),
    "pk_document_occurrences": (
        "document_occurrences",
        "p",
        ("id",),
        None,
        (),
        None,
    ),
    "pk_document_parses": ("document_parses", "p", ("id",), None, (), None),
    "pk_document_relations": (
        "document_relations",
        "p",
        ("id",),
        None,
        (),
        None,
    ),
    "pk_index_configs": ("index_configs", "p", ("id",), None, (), None),
    "pk_index_runs": ("index_runs", "p", ("id",), None, (), None),
    "pk_search_audit_events": (
        "search_audit_events",
        "p",
        ("id",),
        None,
        (),
        None,
    ),
    "pk_sections": ("sections", "p", ("id",), None, (), None),
    "pk_source_profiles": ("source_profiles", "p", ("id",), None, (), None),
    "uq_api_clients_key_id": ("api_clients", "u", ("key_id",), None, (), None),
    "uq_chunk_embeddings_chunk_id_config_hash": (
        "chunk_embeddings",
        "u",
        ("chunk_id", "embedding_config_hash"),
        None,
        (),
        None,
    ),
    "uq_chunks_section_id_ordinal": (
        "chunks",
        "u",
        ("section_id", "ordinal"),
        None,
        (),
        None,
    ),
    "uq_document_contents_content_hash": (
        "document_contents",
        "u",
        ("content_hash",),
        None,
        (),
        None,
    ),
    "uq_document_occurrences_run_id_id": (
        "document_occurrences",
        "u",
        ("run_id", "id"),
        None,
        (),
        None,
    ),
    "uq_document_occurrences_run_id_source_path": (
        "document_occurrences",
        "u",
        ("run_id", "source_path"),
        None,
        (),
        None,
    ),
    "uq_document_parses_content_parser_chunk_config": (
        "document_parses",
        "u",
        ("content_id", "parser_version", "chunk_config_hash"),
        None,
        (),
        None,
    ),
    "uq_index_configs_config_hash": (
        "index_configs",
        "u",
        ("config_hash",),
        None,
        (),
        None,
    ),
    "uq_index_runs_source_profile_id_id": (
        "index_runs",
        "u",
        ("source_profile_id", "id"),
        None,
        (),
        None,
    ),
    "uq_sections_parse_id_id": (
        "sections",
        "u",
        ("parse_id", "id"),
        None,
        (),
        None,
    ),
    "uq_sections_parse_id_ordinal": (
        "sections",
        "u",
        ("parse_id", "ordinal"),
        None,
        (),
        None,
    ),
    "uq_source_profiles_source_key": (
        "source_profiles",
        "u",
        ("source_key",),
        None,
        (),
        None,
    ),
    "fk_chunk_embeddings_chunk_id": (
        "chunk_embeddings",
        "f",
        ("chunk_id",),
        "chunks",
        ("id",),
        "c",
    ),
    "fk_chunks_section_id": (
        "chunks",
        "f",
        ("section_id",),
        "sections",
        ("id",),
        "c",
    ),
    "fk_client_source_grants_client_id": (
        "client_source_grants",
        "f",
        ("client_id",),
        "api_clients",
        ("id",),
        "c",
    ),
    "fk_client_source_grants_source_profile_id": (
        "client_source_grants",
        "f",
        ("source_profile_id",),
        "source_profiles",
        ("id",),
        "r",
    ),
    "fk_document_occurrences_content_id": (
        "document_occurrences",
        "f",
        ("content_id",),
        "document_contents",
        ("id",),
        "r",
    ),
    "fk_document_occurrences_run_id": (
        "document_occurrences",
        "f",
        ("run_id",),
        "index_runs",
        ("id",),
        "c",
    ),
    "fk_document_parses_content_id": (
        "document_parses",
        "f",
        ("content_id",),
        "document_contents",
        ("id",),
        "c",
    ),
    "fk_document_relations_evidence_occurrence": (
        "document_relations",
        "f",
        ("run_id", "evidence_source_path"),
        "document_occurrences",
        ("run_id", "source_path"),
        "c",
    ),
    "fk_document_relations_from_occurrence": (
        "document_relations",
        "f",
        ("run_id", "from_occurrence_id"),
        "document_occurrences",
        ("run_id", "id"),
        "c",
    ),
    "fk_document_relations_run_id": (
        "document_relations",
        "f",
        ("run_id",),
        "index_runs",
        ("id",),
        "c",
    ),
    "fk_document_relations_to_occurrence": (
        "document_relations",
        "f",
        ("run_id", "to_occurrence_id"),
        "document_occurrences",
        ("run_id", "id"),
        "c",
    ),
    "fk_index_runs_index_config_id": (
        "index_runs",
        "f",
        ("index_config_id",),
        "index_configs",
        ("id",),
        "r",
    ),
    "fk_index_runs_source_profile_id": (
        "index_runs",
        "f",
        ("source_profile_id",),
        "source_profiles",
        ("id",),
        "r",
    ),
    "fk_search_audit_events_client_id": (
        "search_audit_events",
        "f",
        ("client_id",),
        "api_clients",
        ("id",),
        "r",
    ),
    "fk_search_audit_events_source_profile_id": (
        "search_audit_events",
        "f",
        ("source_profile_id",),
        "source_profiles",
        ("id",),
        "r",
    ),
    "fk_sections_parse_id": (
        "sections",
        "f",
        ("parse_id",),
        "document_parses",
        ("id",),
        "c",
    ),
    "fk_sections_parse_id_parent_section_id": (
        "sections",
        "f",
        ("parse_id", "parent_section_id"),
        "sections",
        ("parse_id", "id"),
        "c",
    ),
    "fk_source_profiles_active_index_run": (
        "source_profiles",
        "f",
        ("id", "active_index_run_id"),
        "index_runs",
        ("source_profile_id", "id"),
        "r",
    ),
}

EXPECTED_CHECK_CONSTRAINTS = {
    "ck_api_clients_key_id_length": (
        "api_clients",
        ("key_id",),
        "CHECK (char_length(key_id::text) = 16)",
    ),
    "ck_api_clients_name_non_blank": (
        "api_clients",
        ("name",),
        "CHECK (name ~ '[^[:space:]]'::text)",
    ),
    "ck_api_clients_status": (
        "api_clients",
        ("status",),
        "CHECK (status = ANY (ARRAY['active'::text, 'disabled'::text, 'revoked'::text]))",
    ),
    "ck_api_clients_token_hash_length": (
        "api_clients",
        ("token_hash",),
        "CHECK (octet_length(token_hash) = 32)",
    ),
    "ck_chunk_embeddings_config_hash_sha256": (
        "chunk_embeddings",
        ("embedding_config_hash",),
        "CHECK (embedding_config_hash::text ~ '^[0-9a-f]{64}$'::text)",
    ),
    "ck_chunk_embeddings_dimension_positive": (
        "chunk_embeddings",
        ("dimension",),
        "CHECK (dimension > 0)",
    ),
    "ck_chunk_embeddings_model_name_non_blank": (
        "chunk_embeddings",
        ("model_name",),
        "CHECK (model_name ~ '[^[:space:]]'::text)",
    ),
    "ck_chunk_embeddings_model_revision_non_blank": (
        "chunk_embeddings",
        ("model_revision",),
        "CHECK (model_revision ~ '[^[:space:]]'::text)",
    ),
    "ck_chunk_embeddings_status_ready": (
        "chunk_embeddings",
        ("status",),
        "CHECK (status = 'ready'::text)",
    ),
    "ck_chunk_embeddings_vector_dimension": (
        "chunk_embeddings",
        ("embedding", "dimension"),
        "CHECK (vector_dims(embedding) = dimension)",
    ),
    "ck_chunks_chunk_hash_sha256": (
        "chunks",
        ("chunk_hash",),
        "CHECK (chunk_hash::text ~ '^[0-9a-f]{64}$'::text)",
    ),
    "ck_chunks_line_range": (
        "chunks",
        ("line_start", "line_end"),
        "CHECK (line_start >= 1 AND line_end >= line_start)",
    ),
    "ck_chunks_ordinal_nonnegative": ("chunks", ("ordinal",), "CHECK (ordinal >= 0)"),
    "ck_chunks_token_count_nonnegative": (
        "chunks",
        ("token_count",),
        "CHECK (token_count >= 0)",
    ),
    "ck_document_contents_byte_size_matches_content": (
        "document_contents",
        ("byte_size", "content"),
        "CHECK (byte_size = octet_length(content))",
    ),
    "ck_document_contents_byte_size_nonnegative": (
        "document_contents",
        ("byte_size",),
        "CHECK (byte_size >= 0)",
    ),
    "ck_document_contents_content_hash_sha256": (
        "document_contents",
        ("content_hash",),
        "CHECK (content_hash::text ~ '^[0-9a-f]{64}$'::text)",
    ),
    "ck_document_occurrences_decision_state": (
        "document_occurrences",
        ("decision_state",),
        "CHECK (decision_state = ANY (ARRAY['confirmed'::text, 'draft'::text, 'unknown'::text]))",
    ),
    "ck_document_occurrences_owner_domain": (
        "document_occurrences",
        ("owner_domain",),
        "CHECK (owner_domain = ANY (ARRAY['docs'::text, 'uiux'::text]))",
    ),
    "ck_document_occurrences_source_path_non_blank": (
        "document_occurrences",
        ("source_path",),
        "CHECK (source_path ~ '[^[:space:]]'::text)",
    ),
    "ck_document_occurrences_version_scope": (
        "document_occurrences",
        ("version_scope",),
        "CHECK (version_scope = ANY (ARRAY['current'::text, 'historical'::text]))",
    ),
    "ck_document_parses_chunk_config_hash_sha256": (
        "document_parses",
        ("chunk_config_hash",),
        "CHECK (chunk_config_hash::text ~ '^[0-9a-f]{64}$'::text)",
    ),
    "ck_document_parses_artifact_hash_sha256": (
        "document_parses",
        ("artifact_hash",),
        "CHECK (artifact_hash::text ~ '^[0-9a-f]{64}$'::text)",
    ),
    "ck_document_parses_chunk_count_nonnegative": (
        "document_parses",
        ("chunk_count",),
        "CHECK (chunk_count >= 0)",
    ),
    "ck_document_parses_parser_version_non_blank": (
        "document_parses",
        ("parser_version",),
        "CHECK (parser_version ~ '[^[:space:]]'::text)",
    ),
    "ck_document_parses_section_count_positive": (
        "document_parses",
        ("section_count",),
        "CHECK (section_count > 0)",
    ),
    "ck_document_relations_evidence_line_range": (
        "document_relations",
        ("evidence_line_start", "evidence_line_end"),
        "CHECK (evidence_line_start >= 1 AND evidence_line_end >= evidence_line_start)",
    ),
    "ck_document_relations_evidence_source_path_non_blank": (
        "document_relations",
        ("evidence_source_path",),
        "CHECK (evidence_source_path ~ '[^[:space:]]'::text)",
    ),
    "ck_document_relations_relation_type": (
        "document_relations",
        ("relation_type",),
        "CHECK (relation_type = ANY (ARRAY['supersedes'::text, 'potential_conflict'::text]))",
    ),
    "ck_index_configs_chunk_config_object": (
        "index_configs",
        ("chunk_config",),
        "CHECK (jsonb_typeof(chunk_config) = 'object'::text)",
    ),
    "ck_index_configs_config_hash_sha256": (
        "index_configs",
        ("config_hash",),
        "CHECK (config_hash::text ~ '^[0-9a-f]{64}$'::text)",
    ),
    "ck_index_configs_embedding_config_object": (
        "index_configs",
        ("embedding_config",),
        "CHECK (jsonb_typeof(embedding_config) = 'object'::text)",
    ),
    "ck_index_configs_parser_config_object": (
        "index_configs",
        ("parser_config",),
        "CHECK (jsonb_typeof(parser_config) = 'object'::text)",
    ),
    "ck_index_configs_rrf_config_object": (
        "index_configs",
        ("rrf_config",),
        "CHECK (jsonb_typeof(rrf_config) = 'object'::text)",
    ),
    "ck_index_configs_tokenizer_config_object": (
        "index_configs",
        ("tokenizer_config",),
        "CHECK (jsonb_typeof(tokenizer_config) = 'object'::text)",
    ),
    "ck_index_runs_commit_sha_git": (
        "index_runs",
        ("commit_sha",),
        "CHECK (commit_sha::text ~ '^[0-9a-f]{40}$'::text)",
    ),
    "ck_index_runs_lifecycle_activated_at": (
        "index_runs",
        ("status", "activated_at"),
        "CHECK ((status <> ALL (ARRAY['active'::text, 'previous'::text, "
        "'archived'::text])) OR activated_at IS NOT NULL)",
    ),
    "ck_index_runs_stats_object": (
        "index_runs",
        ("stats",),
        "CHECK (jsonb_typeof(stats) = 'object'::text)",
    ),
    "ck_index_runs_status": (
        "index_runs",
        ("status",),
        "CHECK (status = ANY (ARRAY['building'::text, 'ready'::text, "
        "'active'::text, 'previous'::text, 'archived'::text, 'failed'::text]))",
    ),
    "ck_search_audit_events_commit_sha_git": (
        "search_audit_events",
        ("commit_sha",),
        "CHECK (commit_sha::text ~ '^[0-9a-f]{40}$'::text)",
    ),
    "ck_search_audit_events_embedding_ms_nonnegative": (
        "search_audit_events",
        ("embedding_ms",),
        "CHECK (embedding_ms >= 0)",
    ),
    "ck_search_audit_events_filters_object": (
        "search_audit_events",
        ("filters",),
        "CHECK (jsonb_typeof(filters) = 'object'::text)",
    ),
    "ck_search_audit_events_keyword_ms_nonnegative": (
        "search_audit_events",
        ("keyword_ms",),
        "CHECK (keyword_ms >= 0)",
    ),
    "ck_search_audit_events_query_hmac_length": (
        "search_audit_events",
        ("query_hmac",),
        "CHECK (octet_length(query_hmac) = 32)",
    ),
    "ck_search_audit_events_request_id_non_blank": (
        "search_audit_events",
        ("request_id",),
        "CHECK (request_id ~ '[^[:space:]]'::text)",
    ),
    "ck_search_audit_events_result_count_nonnegative": (
        "search_audit_events",
        ("result_count",),
        "CHECK (result_count >= 0)",
    ),
    "ck_search_audit_events_rrf_ms_nonnegative": (
        "search_audit_events",
        ("rrf_ms",),
        "CHECK (rrf_ms >= 0)",
    ),
    "ck_search_audit_events_status": (
        "search_audit_events",
        ("status",),
        "CHECK (status = ANY (ARRAY['ok'::text, 'no_evidence'::text]))",
    ),
    "ck_search_audit_events_total_ms_nonnegative": (
        "search_audit_events",
        ("total_ms",),
        "CHECK (total_ms >= 0)",
    ),
    "ck_search_audit_events_vector_ms_nonnegative": (
        "search_audit_events",
        ("vector_ms",),
        "CHECK (vector_ms >= 0)",
    ),
    "ck_sections_level_range": (
        "sections",
        ("level",),
        "CHECK (level >= 0 AND level <= 6)",
    ),
    "ck_sections_line_range": (
        "sections",
        ("line_start", "line_end"),
        "CHECK (line_start >= 1 AND line_end >= line_start)",
    ),
    "ck_sections_ordinal_nonnegative": (
        "sections",
        ("ordinal",),
        "CHECK (ordinal >= 0)",
    ),
    "ck_source_profiles_exclude_patterns_array": (
        "source_profiles",
        ("exclude_patterns",),
        "CHECK (jsonb_typeof(exclude_patterns) = 'array'::text)",
    ),
    "ck_source_profiles_include_patterns_array": (
        "source_profiles",
        ("include_patterns",),
        "CHECK (jsonb_typeof(include_patterns) = 'array'::text)",
    ),
    "ck_source_profiles_source_key_non_blank": (
        "source_profiles",
        ("source_key",),
        "CHECK (source_key ~ '[^[:space:]]'::text)",
    ),
}

EXPECTED_EXPLICIT_INDEXES = {
    "ix_chunks_search_text_trgm": (
        "chunks",
        "gin",
        ("search_text",),
        ("gin_trgm_ops",),
    ),
    "ix_client_source_grants_source_profile_id": (
        "client_source_grants",
        "btree",
        ("source_profile_id",),
        ("uuid_ops",),
    ),
    "ix_document_occurrences_content_id": (
        "document_occurrences",
        "btree",
        ("content_id",),
        ("uuid_ops",),
    ),
    "ix_document_relations_evidence": (
        "document_relations",
        "btree",
        ("run_id", "evidence_source_path"),
        ("uuid_ops", "text_ops"),
    ),
    "ix_document_relations_from": (
        "document_relations",
        "btree",
        ("run_id", "from_occurrence_id"),
        ("uuid_ops", "uuid_ops"),
    ),
    "ix_document_relations_to": (
        "document_relations",
        "btree",
        ("run_id", "to_occurrence_id"),
        ("uuid_ops", "uuid_ops"),
    ),
    "ix_index_runs_index_config_id": (
        "index_runs",
        "btree",
        ("index_config_id",),
        ("uuid_ops",),
    ),
    "ix_index_runs_source_status": (
        "index_runs",
        "btree",
        ("source_profile_id", "status"),
        ("uuid_ops", "text_ops"),
    ),
    "uq_index_runs_one_active_per_source": (
        "index_runs",
        "btree",
        ("source_profile_id",),
        ("uuid_ops",),
    ),
    "uq_index_runs_one_previous_per_source": (
        "index_runs",
        "btree",
        ("source_profile_id",),
        ("uuid_ops",),
    ),
    "ix_search_audit_events_client_id": (
        "search_audit_events",
        "btree",
        ("client_id",),
        ("uuid_ops",),
    ),
    "ix_search_audit_events_source_profile_id": (
        "search_audit_events",
        "btree",
        ("source_profile_id",),
        ("uuid_ops",),
    ),
    "ix_sections_parent_section_id": (
        "sections",
        "btree",
        ("parent_section_id",),
        ("uuid_ops",),
    ),
    "ix_source_profiles_active_index_run_id": (
        "source_profiles",
        "btree",
        ("active_index_run_id",),
        ("uuid_ops",),
    ),
}

EXPECTED_NON_ID_DEFAULTS = {
    ("api_clients", "created_at"): "now()",
    ("api_clients", "status"): "'active'::text",
    ("chunk_embeddings", "status"): "'ready'::text",
    ("index_runs", "started_at"): "now()",
    ("index_runs", "stats"): "'{}'::jsonb",
    ("index_runs", "status"): "'building'::text",
    ("search_audit_events", "filters"): "'{}'::jsonb",
    ("search_audit_events", "occurred_at"): "now()",
    ("search_audit_events", "returned_chunk_ids"): "'{}'::uuid[]",
    ("source_profiles", "exclude_patterns"): "'[]'::jsonb",
    ("source_profiles", "include_patterns"): "'[]'::jsonb",
}
